[snowflake]
user='SA220_SYSTEMUSER'
account='ip16082.ap-northeast-1.aws'
role='SA_SA220_ROLE'
warehouse='WH_SA220'
scheme='SA220_TS3_DL'
private_key_file='C:\Snowflake_Downloader-2.0.0-win-amd64\rsa_key.p8'
private_key_file_pwd='p$1mHN{E8s*er7SlIv]j)RN4x9{{&R7c'